version: '1.0.0'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autodiksi-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - HOSTNAME_URL=${HOSTNAME_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - API_KEY_EMAIL=${API_KEY_EMAIL}
      - API_KEY_PASSWORD=${API_KEY_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION=${OPENAI_ORGANIZATION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
